db
bakutinamari/test_guru pull request #2
Opened 2022-02-03 20:52 UTC by bakutinamari

2022-02-04 07:23 UTC, BubuntuClu requested changes

2022-02-04 07:23 UTC, BubuntuClu commented on app/models/test.rb
> +  def self.name_tests(title)
лучше всегда проверять написаный код. этот код можно вызвать через `rails c`. к чему применяется условие `where`? как в запросе появились категории?
нужно написать валидный руби код

2022-02-04 07:23 UTC, BubuntuClu commented on app/models/user.rb
> +		tests.where(level: level)
тоже самое и тут. это нерабочий код. что такое `tests`? откуда оно взялось?

2022-02-04 07:23 UTC, BubuntuClu commented on db/seeds.rb
> +                   ])
еще нужно создать вопросы и ответы

2022-02-07 06:51 UTC, BubuntuClu requested changes

2022-02-07 06:51 UTC, BubuntuClu commented on app/models/test.rb
> +  def initialize(level, title)
у тебя класс наследуется от ApplicationRecord, не стоит переопределять инициалайзер. да и зачем это делать?

2022-02-07 06:51 UTC, BubuntuClu commented on app/models/test.rb
> +    Test.where(category_id == category.id).order(id: :desc).pluck(:title)
тут невалидный руби код, в условии `where`. ты в консоле проверяешь код?

и параметром в метод приходит название категории, а не сама категория.

напиши сначала SQL запрос, который сделает то что тебе надо, а потом попробуй перевести его в Active Record. тебе надо будет приджойнить таблицу категорий, чтобы смочь фильтровать по названию категории

2022-02-07 06:51 UTC, BubuntuClu commented on app/models/test.rb
> +  attr_accessor :level, :title
ты же это можешь получить из объекта теста без этого кода, зачем тебе это прописывать? что ты хотел этим получить?

2022-02-07 06:51 UTC, BubuntuClu commented on db/seeds.rb
> +answers = Answer.create([{correct: true, question: questions.first == 'Австралия'},
как ответы могут быть созданы раньше вопросов? у тебя еще не заполнен объект questions, чтобы им оперировать

2022-02-07 06:51 UTC, BubuntuClu commented on app/models/user.rb
>  class User < ApplicationRecord
тут должен быть метод, который ИЗ бд достает все тесты определенного уровня и фильтрует по пользователю. пользователь берется из self так как это инстанс метод.

для реализации "прохождения тестов" тебе нужно реализовать связь многие-ко-многим. это делается через промежуточную таблицу

2022-02-07 06:51 UTC, BubuntuClu commented on app/models/user.rb
> +	def tests_by_level(levels)
мне кажется этот код ты тоже не проверял.
` all_tests self` тут self будет пользователь, а не тест, как ты указал в описании метода `def all_tests(test)`

2022-02-08 06:53 UTC, BubuntuClu requested changes

2022-02-08 06:53 UTC, BubuntuClu commented on app/models/user.rb
> +       self.joins("LEFT JOIN user_tests ON tests.id = test_id").where(tests.level = ?,user_tests.user_id = ?, levels, users)
1 - `where(tests.level = ?,user_tests.user_id = ?, levels, users)`
забыл двойные кавычки в `where` добавить, сейчас тут будет ошибка.

2 - что такое `users`? `levels` это параметр метода, который приходит при вызове метода, а вот `users` что такое?

2022-02-08 06:53 UTC, BubuntuClu requested changes

2022-02-08 06:53 UTC, BubuntuClu commented on db/seeds.rb
> +answers = Answer.create([{correct: true, question: questions.first},
как ответы могут быть созданы раньше вопросов? у тебя еще не заполнен объект questions, чтобы им оперировать

2022-02-08 06:54 UTC, BubuntuClu commented
ты не создал таблицу `users_tests` чтобы ее использовать в запросе

2022-02-10 06:36 UTC, BubuntuClu requested changes

2022-02-10 06:36 UTC, BubuntuClu commented on db/migrate/20220209231654_create_user_tests.rb
> +      t.references :test_id, null: false, foreign_key: true
у тебя нет таблицы `test_id`, у тебя есть таблица `test`. неправильно указал таблицу для связи

2022-02-10 06:36 UTC, BubuntuClu commented on db/migrate/20220209231654_create_user_tests.rb
> +      t.references :user_id, null: false, foreign_key: true
тоже самое и тут

2022-02-10 06:36 UTC, BubuntuClu commented on app/models/user_test.rb
> +  belongs_to :test_id
тут связи неправильно указал,когда поправишь таблицу, то тут будет просто `test`

2022-02-10 06:36 UTC, BubuntuClu commented on app/models/user_test.rb
> +  belongs_to :user_id
аналогично и тут

2022-02-15 07:09 UTC, VidgarVii requested changes

2022-02-15 07:09 UTC, VidgarVii commented on app/models/category.rb
> +
Не хватает ассоциаций. 
Категория имеет тесты

2022-02-15 07:09 UTC, VidgarVii commented on app/models/test.rb
> +
не совсем понимаю
ДЗ определить ассоциации в моделях. Какие-то ассоциации почему-то уже были. Других не появились.
Добавь ассоциации согласно ДЗ. В видео уроках это всё показано

2022-02-15 07:09 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins("LEFT JOIN categories ON tests.category_id = categories.id")
можно (и рекомендуется)  писать так:
```ruby
joins(...)...
```
т.е. без явного указания объекта у которого вызывается метод
потому что в данном случае объектом является класс `Test` и ему равен `self` внутри класс-метода
по дефолту, при вызове метода без указания объекта он вызывается у `self`, т.е. в текущем варианте как раз у `Test`

2022-02-15 07:09 UTC, VidgarVii commented on app/models/test.rb
> +  def self.sort_title_tests(category)
если параметр метода называется category, то подразумевается, что метод принимает объект категории. Но по коду это не так. Работает он явно не с объектом, категории, а с title категории. Исправь описание параметра

2022-02-15 07:09 UTC, VidgarVii commented on db/migrate/20220210213638_create_users.rb
> +      t.integer :age
соблюдай консистентность данных. 
Зачем нам юзер без имени ? Данная миграция позволит создать такого. По факты ты просто сломал миграцию

2022-02-15 07:09 UTC, VidgarVii commented on db/seeds.rb
> +answers = Answer.create([{correct: true, question: questions.first = "Австралия"},
Если переменная не используется, то лучше её не создавать. Затрудняет работу сборщику мусора

2022-02-15 07:09 UTC, VidgarVii commented on db/seeds.rb
> +                         {correct: true, question: questions.last = "c**2 = a**2 + b**2"}
это какой-то новый синтаксис?!
Проверяй работу прежде чем её сдавать

2022-02-15 07:25 UTC, merged